version: '3'
services:

      
  sqlserver:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlserver
    volumes:
      - sqlserverdata:/var/opt/mssql 
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_PID=Developer
      - SA_PASSWORD=8jkGh47hnDw89Haq8LN2


  dictoweb:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: dictowebapi
    environment:
        - DatabaseServer=sqlserver
        - DatabaseName=dictodb
        - DatabaseUser=sa
        - DatabaseNamePassword=8jkGh47hnDw89Haq8LN2
    ports:
        - "5000:80"
    depends_on:
        - sqlserver
  

volumes:
  sqlserverdata:
    external: true    
